name: imu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  network_info_plus: ^4.1.0
  sensors_plus: ^3.1.0
  audioplayers: ^5.1.0
  vibration: ^1.8.3
  vector_math: ^2.1.4
  permission_handler: ^11.0.0  # Para saber la IP local
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
